version: '3'

services:
  app:
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_PORT=${HTTP_PORT}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["npm", "start"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: